const coffee = [
  {
    name: "Aynu",
    profile: "clean",
    characteristic: "round",
    url: "https://impactroasters.dk/pages/about-coffe-coffee-guide",
    image: "./assets/coffee/aynu.png",
    taste: ["chocolate", "spicy", "floral"],
    tastingProfile: ["rounded", "fruit acidity", "nut aroma"],
    processing: ["washed"],
    roastProfile: ["dark roast", "medium roast", "light roast"],
    preparation: [
      "espresso",
      "cafe latte",
      "cappuccino",
      "cortado",
      "flat white",
    ],
    origin: [
      {
        name: "Limu",
        latitude: 9.16702,
        longitude: 36.34015,
        altitudeMin: 1750,
        altitudeMax: 1950,
      },
      {
        name: "Limu Kosa",
        latitude: 8.16638,
        longitude: 37.17096,
        altitudeMin: 1750,
        altitudeMax: 1950,
      },
    ],
    qGrade: 88,
  },
  {
    name: "Beza",
    profile: "rich",
    characteristic: "sweet",
    url: "https://impactroasters.dk/pages/about-coffe-coffee-guide",
    image: "./assets/coffee/beza.png",
    taste: ["chocolate", "spicy", "floral"],
    tastingProfile: ["intense sweetness", "spicy", "forest berry aroma"],
    processing: ["sundried"],
    roastProfile: ["dark roast", "light roast"],
    preparation: [
      "espresso",
      "cafe latte",
      "cappuccino",
      "cortado",
      "flat white",
    ],
    origin: [
      {
        name: "Yirgachefe",
        latitude: 6.16272,
        longitude: 38.20583,
        altitudeMin: 1900,
        altitudeMax: 2100,
      },
      {
        name: "Yirga Chefe",
        latitude: 6.16272,
        longitude: 38.20583,
        altitudeMin: 1700,
        altitudeMax: 1950,
      },
    ],
    qGrade: 92,
  },
  {
    name: "Desta",
    profile: "rich",
    characteristic: "sweet",
    url: "https://impactroasters.dk/pages/about-coffe-coffee-guide",
    image: "./assets/coffee/desta.png",
    taste: ["chocolate", "spicy", "floral"],
    tastingProfile: ["intense sweetness", "floral", "nougat aroma"],
    processing: ["washed", "sundried"],
    roastProfile: ["dark roast"],
    preparation: [
      "espresso",
      "cafe latte",
      "cappuccino",
      "cortado",
      "flat white",
    ],
    origin: [
      {
        name: "Aroresa",
        latitude: 6.33485,
        longitude: 39.00473,
        altitudeMin: 1700,
        altitudeMax: 1950,
      },
      {
        name: "Jimma Agaro",
        latitude: 7.85108,
        longitude: 36.58889,
        altitudeMin: 1650,
        altitudeMax: 1950,
      },
    ],
    qGrade: 87,
  },
  {
    name: "Kaffa",
    profile: "rich",
    characteristic: "round",
    url: "https://impactroasters.dk/pages/about-coffe-coffee-guide",
    image: "./assets/coffee/kaffa.png",
    taste: ["chocolate", "spicy", "floral"],
    tastingProfile: ["forest berries", "delicate sweetness", "chocolate aroma"],
    processing: ["sundried"],
    roastProfile: ["dark roast", "medium roast", "light roast"],
    preparation: [
      "espresso",
      "cafe latte",
      "cappuccino",
      "cortado",
      "flat white",
    ],
    origin: [
      {
        name: "Kaffa",
        latitude: 7.31034,
        longitude: 35.96491,
        altitudeMin: 1400,
        altitudeMax: 2100,
      },
      {
        name: "Gimbo Kimbo",
        latitude: 7.34604,
        longitude: 36.22318,
        altitudeMin: 2100,
        altitudeMax: 1400,
      },
    ],
    qGrade: 89,
  },
  {
    name: "Lomi",
    profile: "clean",
    characteristic: "round",
    url: "https://impactroasters.dk/pages/about-coffe-coffee-guide",
    image: "./assets/coffee/lomi.png",
    taste: ["chocolate", "spicy", "floral"],
    tastingProfile: ["sweet", "fruity", "citrus aroma"],
    processing: ["washed"],
    roastProfile: ["dark roast", "medium roast", "light roast"],
    preparation: [
      "espresso",
      "cafe latte",
      "cappuccino",
      "cortado",
      "flat white",
    ],
    origin: [
      {
        name: "Sidama",
        latitude: 7.03507,
        longitude: 38.47632,
        altitudeMin: 2759,
        altitudeMax: 2829,
      },
      {
        name: "Wendo",
        latitude: 6.60314,
        longitude: 38.41938,
        altitudeMin: 1800,
        altitudeMax: 2000,
      },
    ],
    qGrade: 88,
  },
  {
    name: "Mazaa",
    profile: "rich",
    characteristic: "sweet",
    url: "https://impactroasters.dk/pages/about-coffe-coffee-guide",
    image: "./assets/coffee/mazaa.png",
    taste: ["chocolate", "spicy", "floral"],
    tastingProfile: ["honey", "sweet", "spicy aroma"],
    processing: ["sundried"],
    roastProfile: ["dark roast", "medium roast", "light roast"],
    preparation: [
      "espresso",
      "cafe latte",
      "cappuccino",
      "cortado",
      "flat white",
    ],
    origin: [
      {
        name: "Guji",
        latitude: 9.00382,
        longitude: 35.50255,
        altitudeMin: 2000,
        altitudeMax: 1900,
      },
      {
        name: "Oromia",
        latitude: 7.546,
        longitude: 40.6347,
        altitudeMin: 2350,
        altitudeMax: 1500,
      },
    ],
    qGrade: 87,
  },
  {
    name: "Nehi",
    profile: "clean",
    characteristic: "sweet",
    url: "https://impactroasters.dk/pages/about-coffe-coffee-guide",
    image: "./assets/coffee/nehi.png",
    taste: ["chocolate", "spicy", "floral"],
    tastingProfile: ["sweet", "fruity", "chocolate aroma"],
    processing: ["washed"],
    roastProfile: ["dark roast", "medium roast", "light roast"],
    preparation: [
      "espresso",
      "cafe latte",
      "cappuccino",
      "cortado",
      "flat white",
    ],
    origin: [
      {
        name: "Sidama",
        latitude: 7.03507,
        longitude: 38.47632,
        altitudeMin: 2759,
        altitudeMax: 2829,
      },
      {
        name: "Aroresa",
        latitude: 6.33485,
        longitude: 39.00473,
        altitudeMin: 1700,
        altitudeMax: 1950,
      },
    ],
    qGrade: 87,
  },
  {
    name: "Saba",
    profile: "clean",
    characteristic: "acidic",
    url: "https://impactroasters.dk/pages/about-coffe-coffee-guide",
    image: "./assets/coffee/saba.png",
    taste: ["chocolate", "spicy", "floral"],
    tastingProfile: ["slightly acidic", "floral", "citrus aroma"],
    processing: ["washed"],
    roastProfile: ["dark roast", "medium roast", "light roast"],
    preparation: [
      "espresso",
      "cafe latte",
      "cappuccino",
      "cortado",
      "flat white",
    ],
    origin: [
      {
        name: "Yirgachefe",
        latitude: 6.16272,
        longitude: 38.20583,
        altitudeMin: 1900,
        altitudeMax: 2100,
      },
      {
        name: "Aroma",
        latitude: 11.59985,
        longitude: 37.37529,
        altitudeMin: 1800,
        altitudeMax: 2000,
      },
    ],
    qGrade: 88,
  },
  {
    name: "Worke",
    profile: "clean",
    characteristic: "acidic",
    url: "https://impactroasters.dk/pages/about-coffe-coffee-guide",
    image: "./assets/coffee/worke.png",
    taste: ["chocolate", "spicy", "floral"],
    tastingProfile: ["slightly acidic", "floral", "citrus aroma"],
    processing: ["washed"],
    roastProfile: ["dark roast", "medium roast", "light roast"],
    preparation: [
      "espresso",
      "cafe latte",
      "cappuccino",
      "cortado",
      "flat white",
    ],
    origin: [
      {
        name: "Yirgachefe",
        latitude: 6.16272,
        longitude: 38.20583,
        altitudeMin: 1900,
        altitudeMax: 2100,
      },
      {
        name: "Aroma",
        latitude: 11.59985,
        longitude: 37.37529,
        altitudeMin: 1800,
        altitudeMax: 2000,
      },
    ],
    qGrade: 88,
  },
  {
    name: "Zala",
    profile: "clean",
    characteristic: "sweet",
    url: "https://impactroasters.dk/pages/about-coffe-coffee-guide",
    image: "./assets/coffee/zala.png",
    taste: ["chocolate", "spicy", "floral"],
    tastingProfile: ["fresh citrus", "floral", "fruity aroma"],
    processing: ["washed"],
    roastProfile: ["dark roast", "medium roast", "light roast"],
    preparation: [
      "espresso",
      "cafe latte",
      "cappuccino",
      "cortado",
      "flat white",
    ],
    origin: [
      {
        name: "Guji",
        latitude: 9.00382,
        longitude: 35.50255,
        altitudeMin: 2000,
        altitudeMax: 1900,
      },
      {
        name: "Oromia",
        latitude: 7.546,
        longitude: 40.6347,
        altitudeMin: 1500,
        altitudeMax: 2350,
      },
    ],
    qGrade: 87,
  },
  {
    name: "Zenu",
    profile: "rich",
    characteristic: "acidic",
    url: "https://impactroasters.dk/pages/about-coffe-coffee-guide",
    image: "./assets/coffee/zenu.png",
    taste: ["chocolate", "spicy", "floral"],
    tastingProfile: ["slightly acidic", "floral", "nougat aroma"],
    processing: ["sundried"],
    roastProfile: ["dark roast"],
    preparation: [
      "espresso",
      "cafe latte",
      "cappuccino",
      "cortado",
      "flat white",
    ],
    origin: [
      {
        name: "Jimma ",
        latitude: 7.6751,
        longitude: 36.83514,
        altitudeMin: 1650,
        altitudeMax: 1950,
      },
      {
        name: "Jimma Agaro",
        latitude: 7.85108,
        longitude: 36.58889,
        altitudeMin: 1700,
        altitudeMax: 1950,
      },
    ],
    qGrade: 82,
  },
];

export default coffee;
